blobs:
  - provider: gs
    bucket: calyptia_cli_bucket
    folder: "releases/{{.Version}}"

builds:
  - main: ./cmd/calyptia
    id: calyptia
    binary: calyptia
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

universal_binaries:
  - replace: true

brews:
  - name: calyptia
    description: Calyptia Cloud CLI
    homepage: https://github.com/calyptia/cli
    tap:
      owner: calyptia
      name: homebrew-tap
    folder: Formula
