upx:
  -
    ids: [ calyptia ]
    enabled: true
    goos: [ linux, windows ] # skip darwin (macOS 13.x Ventura is not support now)
    goarch: [ amd64, arm64 ]

builds:
  - main: .
    id: calyptia
    env:
      - CGO_ENABLED=0
    binary: calyptia
    ldflags:
      - -s -w -X github.com/calyptia/cli/cmd/version.Version={{.Version}}
    gcflags:
      - all=-C -l -B
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

universal_binaries:
  - replace: true
    id: calyptia
    name_template: calyptia

brews:
  - name: calyptia
    alternative_names:
      - calyptia@{{ .Version }}
      - calyptia@{{ .Major }}
    description: Calyptia Cloud CLI
    homepage: https://github.com/chronosphereio/calyptia-cli
    repository:
      owner: chronosphereio
      name: calyptia-homebrew-tap
    directory: Formula
    license: Apache-2.0
    test: |
          system "#{bin}/calyptia version"
