---
name: Reusable workflow to update our local version with the specified one

on:
  workflow_call:
    inputs:
      ref:
        description: The commit, SHA or branch to use in this repository.
        required: false
        type: string
        default: main
      core-operator-version:
        description: The new version to specify.
        required: true
        type: string
      manifest-artefact:
        description: The artefact to download with the manifest in it.
        required: true
        type: string
    secrets:
      token:
        description: The Github token or similar to authenticate with for the code.
        required: true

jobs:
  update-core-fluent-release:
    name: Update Core Operator version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          repository: calyptia/cli

      - name: Update default Core Operator version
        run: |
          sed -i -E "s/DefaultCoreOperatorDockerImageTag = .*$/DefaultCoreOperatorDockerImageTag = \"$NEW_VERSION\"/g" cmd/utils/utils.go
          sed -i -E "s/DefaultCoreOperatorToCloudDockerImageTag = .*$/DefaultCoreOperatorToCloudDockerImageTag = \"$NEW_VERSION\"/g" cmd/utils/utils.go
          sed -i -E "s/DefaultCoreOperatorFromCloudDockerImageTag = .*$/DefaultCoreOperatorFromCloudDockerImageTag = \"$NEW_VERSION\"/g" cmd/utils/utils.go

          cat cmd/utils/utils.go
        env:
          NEW_VERSION: ${{ inputs.core-operator-version }}
        shell: bash

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.manifest-artefact }}
          path: cmd/operator

      - name: Generate PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'ci: update to latest Core Operator version'
          signoff: true
          branch: ci_update_core_operator_version
          delete-branch: true
          title: 'ci: update to latest Core Operator version'
          token: ${{ secrets.token }}
          labels: ci,automerge
          body: |
            Update to latest Core Operator version: ${{ inputs.core-operator-version }}

            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        shell: bash

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.token }}
