---
name: Check for Core Operator releases to trigger update locally
on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  sync-core-fluent-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Not required as we use CI_PAT directly so we can trigger workflows
      # pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}
          fetch-depth: 0

      - run: ./scripts/update-versions.sh
        shell: bash

      - name: Generate PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'ci: update to latest core-operator version'
          signoff: true
          branch: ci_update_core_operator
          delete-branch: true
          title: 'ci: update to latest Calyptia Core Operator version'
          # We need workflows permission so have to use the CI_PAT
          token: ${{ secrets.CI_PAT }}
          labels: ci,automerge
          body: |
            Update Calyptia Core Operator version: ${{ steps.get-core-operator-release.outputs.tag }}

            - Created by ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
        shell: bash

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
